# Generated by Django 3.2.4 on 2021-06-10 16:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=200)),
                ('why', models.CharField(max_length=200)),
                ('how', models.IntegerField()),
                ('is_public', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=datetime.datetime(2021, 6, 10, 16, 15, 39, 714563, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='PriorityUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='What',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=200)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priorityapi.priority')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 6, 10, 16, 15, 39, 715826, tzinfo=utc))),
                ('ended_on', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='priorityapi.priorityuser')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='priorityapi.priorityuser')),
            ],
        ),
        migrations.AddField(
            model_name='priority',
            name='priority_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priorityapi.priorityuser'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(default=datetime.datetime(2021, 6, 10, 16, 15, 39, 712275, tzinfo=utc))),
                ('goal_date', models.DateField()),
                ('time_spent', models.IntegerField()),
                ('what', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priorityapi.what')),
            ],
        ),
        migrations.CreateModel(
            name='Affirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affirmation', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2021, 6, 10, 16, 15, 39, 711162, tzinfo=utc))),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priorityapi.priority')),
                ('priority_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='priorityapi.priorityuser')),
            ],
        ),
    ]
